import { panIndiaCoverage } from "@/data/pan-india-coverage";

const baseKeywords = [
  "stones gallery",
  "stonesgallery.in",
  "dish impex llp",
  "natural stone supplier bangalore",
  "marble shop bangalore",
  "italian marble bangalore",
  "onyx stone bangalore",
  "quartzite supplier bangalore",
  "stone sculptures bangalore",
  "marble idols bangalore",
  "temple sculptures bangalore",
  "garden statues bangalore",
  "stone artifacts bangalore",
  "custom marble dining table bangalore",
  "marble idols jigani",
  "stone sculptures jigani",
  "marble and granite jp nagar",
  "stone supplier jp nagar",
  "marble shop banashankari",
  "stone sculptures banashankari",
  "marble shop koramangala",
  "natural stone supplier yelahanka",
  "temple statue bangalore",
  "mandir marble idols bangalore",
  "premium stone supplier bangalore",
  "luxury marble bangalore",
  "pistachio marble bangalore",
  "red jasper stone bangalore",
  "dark roast granite bangalore",
  "exterior cladding stone bangalore",
  "stone elevation tiles bangalore",
  "parking tiles granite bangalore",
  "stone for kitchen countertop bangalore",
  "stone wash basin bangalore",
  "garden stone bench bangalore",
  "stone mural bangalore",
  "sculpted temple accessories bangalore",
  "stone gallery near me",
  "stone gallery bangalore",
  "online stone showroom india",
  "marble supplier india",
  "natural stone exporter india",
  "stone sculptures india",
  "marble idols india",
  "temple sculpture manufacturer india",
  "garden statue manufacturer india",
  "italian marble supplier india",
  "onyx stone supplier india",
  "quartzite supplier india",
  "marble handicrafts india",
  "custom stone furniture india",
  "luxury stone decor india",
  "premium stone artifacts india",
  "handcrafted marble idols india",
  "handcrafted stone sculptures india",
  "stone for villa projects bangalore",
  "stone dealer near jigani",
  "stone factory outlet bangalore",
  "wholesale marble bangalore",
  "stone exporter jigani",
  "imported marble bangalore",
  "stone gallery jigani",
  "mandir marble murti bangalore",
  "vastu stone solutions bangalore",
  "exterior stone cladding india",
  "designer marble india",
  "bespoke stone sculpture india",
  "custom stone carving bangalore",
  "stone garden decor bangalore",
  "stone temple construction material bangalore",
];

const coverageKeywords = panIndiaCoverage.flatMap((region) => region.keywords);

export const seoKeywords = Array.from(new Set([...baseKeywords, ...coverageKeywords]));

export const bengaluruHubs = [
  "Jigani Industrial Area",
  "JP Nagar",
  "Banashankari",
  "Jayanagar",
  "Electronic City",
  "Koramangala",
  "Indiranagar",
  "Whitefield",
  "Yelahanka",
  "Sarjapur Road",
];

export const indiaExportFocus = [
  "Luxury marble for pan-India interiors",
  "Custom temple sculptures for global projects",
  "Handcrafted stone furniture for boutique hotels",
  "Natural stone exporter with end-to-end logistics",
];

export const panIndiaCities = panIndiaCoverage;
